# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZUURcvvxC2p3eCTNKbE--rmwj_ob5ed
"""

import torch
print(torch.cuda.is_available())

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# 数据预处理：把图片变成 Tensor
transform = transforms.ToTensor()

# 下载训练数据
train_dataset = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

# 下载测试数据
test_dataset = datasets.MNIST(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

# 批量读取
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

print("训练集大小:", len(train_dataset))
print("测试集大小:", len(test_dataset))

import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()

        # 把 28x28 图片拉平成 784
        self.flatten = nn.Flatten()

        # 第一层：784 -> 128
        self.fc1 = nn.Linear(28*28, 128)
        self.relu1 = nn.ReLU()

        # 第二层：128 -> 64
        self.fc2 = nn.Linear(128, 64)
        self.relu2 = nn.ReLU()

        # 第三层：64 -> 10
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        return x

model = MLP()

print(model)

import torch.optim as optim

# 损失函数（分类问题常用）
criterion = nn.CrossEntropyLoss()

# 优化器（升级版梯度下降）
optimizer = optim.Adam(model.parameters(), lr=0.001)

print("损失函数和优化器已定义")

epochs = 5

for epoch in range(epochs):
    model.train()   # 进入训练模式
    total_loss = 0

    for images, labels in train_loader:

        # 前向传播
        outputs = model(images)

        # 计算损失
        loss = criterion(outputs, labels)

        # 清空梯度
        optimizer.zero_grad()

        # 反向传播
        loss.backward()

        # 更新参数
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader):.4f}")

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print("测试准确率: {:.2f}%".format(accuracy))

torch.save(model.state_dict(), "model.pth")
print("模型已保存为 model.pth")

import random

# 随机选一张测试图片
idx = random.randint(0, len(test_dataset)-1)
image, label = test_dataset[idx]

model.eval()

with torch.no_grad():
    output = model(image.unsqueeze(0))
    _, predicted = torch.max(output, 1)

print("真实标签:", label)
print("预测结果:", predicted.item())

import random

# 随机选一张测试图片
idx = random.randint(0, len(test_dataset)-1)
image, label = test_dataset[idx]

model.eval()

with torch.no_grad():
    output = model(image.unsqueeze(0))
    _, predicted = torch.max(output, 1)

print("真实标签:", label)
print("预测结果:", predicted.item())